// ========================================================
// isoedu AI Drive & Certification Radar - Comprehensive Mock Data
// Reflecting 15 production mockup screens
// ========================================================

import { RICH_DOCUMENT_CONTENTS, CONSULTING_DOMAINS } from './richDocumentContents.js';
export { CONSULTING_DOMAINS };

export const INITIAL_COMPANIES = [
  { id: 'comp-1', name: '(주)아이소에듀', industry: '교육 및 SaaS 솔루션', status: 'Active', isCurrent: true },
  { id: 'comp-2', name: '에듀캠퍼스(주)', industry: '기업 직무 교육', status: 'Normal', isCurrent: false },
  { id: 'comp-3', name: '스마트러닝 솔루션즈', industry: '에듀테크 플랫폼', status: 'Normal', isCurrent: false },
  { id: 'comp-4', name: 'ISO EDU USA, Inc.', industry: '해외 인증 컨설팅', status: 'Normal', isCurrent: false },
  { id: 'comp-5', name: '아이소에듀 베트남', industry: '글로벌 교육 사업', status: 'Normal', isCurrent: false },
];

export const WORKSPACES_DATA = [
  { id: 'ws-1', name: 'Demo Workspace', desc: 'isoedu 데모 워크스페이스입니다.', members: 56, docCount: 342, storage: '45.2 GB', status: '활성', createdAt: '2024-01-15', color: 'bg-blue-600' },
  { id: 'ws-2', name: 'Marketing Team', desc: '마케팅 팀 문서 관리 공간', members: 24, docCount: 156, storage: '12.8 GB', status: '활성', createdAt: '2024-02-03', color: 'bg-emerald-600' },
  { id: 'ws-3', name: 'Project Alpha', desc: '프로젝트 알파 관련 문서 저장소', members: 18, docCount: 98, storage: '8.7 GB', status: '활성', createdAt: '2024-03-11', color: 'bg-indigo-600' },
  { id: 'ws-4', name: 'HR Department', desc: '인사 관련 문서 관리', members: 32, docCount: 210, storage: '23.4 GB', status: '비활성', createdAt: '2023-11-20', color: 'bg-amber-600' },
  { id: 'ws-5', name: 'Finance Team', desc: '재무 및 회계 문서 관리', members: 28, docCount: 184, storage: '15.6 GB', status: '활성', createdAt: '2024-04-05', color: 'bg-rose-600' },
];

export const CERTIFICATION_CATEGORIES = [
  { code: 'ALL', name: '전체 규격', badge: 'ALL' },
  { code: 'ISO_9001', name: 'ISO 9001 (품질경영)', badge: '9001', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { code: 'ISO_14001', name: 'ISO 14001 (환경경영)', badge: '14001', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { code: 'ISO_27001', name: 'ISO 27001 (정보보안)', badge: '27001', color: 'bg-rose-50 text-rose-700 border-rose-200' },
  { code: 'ISO_45001', name: 'ISO 45001 (안전보건)', badge: '45001', color: 'bg-amber-50 text-amber-700 border-amber-200' },
  { code: 'ISO_50001', name: 'ISO 50001 (에너지)', badge: '50001', color: 'bg-purple-50 text-purple-700 border-purple-200' },
];

export const HIERARCHY_LEVELS = [
  { id: 'ALL', name: '전체 계층', countKey: 'all', desc: '모든 ISO 등록 문서' },
  { id: 'LEVEL_1', name: '1계층 매뉴얼', countKey: 'manual', icon: 'BookOpen', desc: '경영시스템 기본 방침 기술' },
  { id: 'LEVEL_2', name: '2계층 절차서', countKey: 'procedure', icon: 'GitPullRequest', desc: '업무 책임과 수행 절차 규정' },
  { id: 'LEVEL_3', name: '3계층 지침서', countKey: 'instruction', icon: 'FileText', desc: '실무 수행 세부 작업 지침' },
  { id: 'LEVEL_4', name: '4계층 기록/양식', countKey: 'records', icon: 'ClipboardCheck', desc: '데이터 수집 및 심사 증빙' },
];

// 최상단 긴급 리스크 알림 티커 데이터 (시안 8번)
export const EMERGENCY_RISK_TICKERS = [
  {
    id: 't-1',
    severity: 'CRITICAL',
    title: 'ISO 45001 인증서 만료 D-15일',
    deadline: '2024-06-15',
    dDay: 15,
    consequence: '미갱신 시 최대 1,000만원 과태료 및 입찰 참가 제한',
    penaltyAmount: '최대 1,000만원',
    docId: 'doc-m-03'
  },
  {
    id: 't-2',
    severity: 'WARNING',
    title: '개인정보보호 교육 미이수자 12명',
    deadline: '2024-06-30',
    dDay: 30,
    consequence: '미이수 시 법정 과태료 300만원 (1인당)',
    penaltyAmount: '과태료 300만원 (1인당)',
    docId: 'doc-f-02'
  },
  {
    id: 't-3',
    severity: 'CRITICAL',
    title: '소방점검 결과보고서 미제출 (D+1 만료)',
    deadline: '2025-05-18',
    dDay: -1,
    consequence: '미제출 시 500만원 이하 과태료 즉시 부과',
    penaltyAmount: '과태료 500만원 이하',
    docId: 'doc-cert-01'
  },
  {
    id: 't-4',
    severity: 'WARNING',
    title: 'ISO 14001 인증서 만료 D-30일',
    deadline: '2024-06-20',
    dDay: 30,
    consequence: '미갱신 시 공공조달 입찰 가점 즉시 미적용',
    penaltyAmount: '입찰 가점 미적용',
    docId: 'doc-m-02'
  }
];

// 만기 레이더 방사형 차트 데이터 (시안 6번)
export const RADAR_RISK_METRICS = {
  categories: [
    { label: '인증서', score: 72, max: 100, color: '#f59e0b', status: '위험' },
    { label: '계약서', score: 46, max: 100, color: '#eab308', status: '주의' },
    { label: '정책 및 절차', score: 68, max: 100, color: '#10b981', status: '주의' },
    { label: '교육 기록', score: 81, max: 100, color: '#ef4444', status: '고위험' },
    { label: '기타 문서', score: 55, max: 100, color: '#3b82f6', status: '정상' }
  ],
  trend: [
    { date: '5월 19일', score: 58 },
    { date: '5월 23일', score: 70 },
    { date: '5월 30일', score: 78 }, // 최고 리스크
    { date: '6월 6일', score: 64 },
    { date: '6월 13일', score: 52 },
    { date: '6월 20일', score: 42 }  // 최저 리스크
  ],
  maxScore: 78,
  minScore: 42
};

// ISO 9001 조항 가이드 및 대시보드 진척도 (시안 13, 15번)
export const CLAUSE_PROGRESS_DATA = [
  { clause: '4. 조직의 상황', title: '조직과 그 상황의 이해, 이해관계자 요구', rate: 75.0, status: '우수' },
  { clause: '5. 리더십', title: '리더십과 의지표명, 품질방침, 역할과 책임', rate: 62.5, status: '진행중' },
  { clause: '6. 기획', title: '리스크 및 기회 관리, 품질목표 및 달성기획', rate: 66.7, status: '진행중' },
  { clause: '7. 지원', title: '자원, 역량, 인식, 의사소통, 문서화된 정보', rate: 70.0, status: '우수' },
  { clause: '8. 운용', title: '운용 기획 및 관리, 제품/서비스 요구사항 관리', rate: 64.3, status: '진행중' },
  { clause: '9. 성과 평가', title: '모니터링, 측정, 분석 및 내부심사, 경영검토', rate: 71.4, status: '우수' },
  { clause: '10. 개선', title: '부적합 및 시정조치, 지속적 개선', rate: 60.0, status: '요주의' },
];

// 시안 1~15번을 아우르는 메인 시드 문서 데이터
const BASE_SEED_DOCUMENTS = [
  // 1. 매뉴얼 (LEVEL_1)
  {
    id: 'doc-m-01',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_1',
    standards: ['ISO_9001'],
    code: 'QM-01',
    title: '품질경영시스템 매뉴얼 (QMS Manual)',
    category: '매뉴얼',
    version: 'v3.0',
    revisionNo: 'Rev. 3.0',
    approvalDate: '2024-05-20',
    lastRevisionDate: '2024-05-20',
    expiryDate: '2025-12-31',
    dDay: 580,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '품질경영팀',
    author: '김철수 차장',
    approver: '홍길동 대표',
    clauseNumber: 'Clause 4~10 전 조항',
    path: '/품질경영시스템/01. 매뉴얼',
    commentsCount: 3,
    coverGradient: 'from-blue-600 via-indigo-600 to-sky-700',
    penaltyRisk: '미준수 시 ISO 9001 정기 사후심사 부적합(Major CAR) 판정 및 인증 효력 정지',
    summary: 'ISO 9001:2015 국제 규격에 따른 품질경영시스템 기본 방침, 프로세스 상호작용 및 품질방침 선언문',
    checklist: [
      { text: '최고경영자 품질방침 서명 및 공표 여부 확인', done: true },
      { text: '조직 상황 및 이해관계자 니즈 매트릭스 갱신', done: true },
      { text: '사내 인트라넷 전파 및 직원 열람 기록 보관', done: true },
    ],
    contentDraft: `[QM-01 품질경영 매뉴얼 v3.0 전문]
1. 적용 범위: (주)아이소에듀 전 사업부
2. 최고경영자의 품질 방침: 고객 중심의 가치 창출과 지속적 개선
3. 리더십 및 조직 체계:
  - 5.1 리더십과 의지표명
  - 5.2 고객 중심: 고객 요구사항 충족 및 만족도 95% 이상 달성
4. 프로세스 맵: 기획 -> 개발 -> 교육운영 -> 사후평가 -> 피드백`
  },
  {
    id: 'doc-m-02',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_1',
    standards: ['ISO_14001'],
    code: 'QM-02',
    title: '환경경영시스템 매뉴얼 (EMS Manual)',
    category: '매뉴얼',
    version: 'v2.1',
    revisionNo: 'Rev. 2.1',
    approvalDate: '2024-04-15',
    lastRevisionDate: '2024-04-15',
    expiryDate: '2025-06-20',
    dDay: 30,
    status: 'EXPIRING',
    docStatus: '승인',
    validityStatus: 'WARNING',
    department: '환경경영팀',
    author: '이민정 과장',
    approver: '김준호 총괄',
    clauseNumber: 'Clause 4~10 환경영향평가',
    path: '/환경경영시스템/01. 매뉴얼',
    commentsCount: 1,
    coverGradient: 'from-emerald-600 via-teal-600 to-green-700',
    penaltyRisk: '환경영향평가 미갱신 시 공공조달 입찰 가점 미적용 및 지자체 불시 점검 리스크',
    summary: 'ISO 14001:2015 환경경영 매뉴얼. 폐기물, 온실가스 감축 목표 및 환경 법규 준수 관리',
    checklist: [
      { text: '환경목표 달성 실적 분기별 측정', done: true },
      { text: '비상사태 대응 훈련 시나리오 최신화', done: false },
      { text: '폐기물 위탁 처리업체 인허가 적격성 검토', done: true }
    ],
    contentDraft: `[QM-02 환경경영 매뉴얼 v2.1]
1. 환경방침: 친환경 에듀테크 서비스 구현 및 탄소배출량 매년 5% 감축
2. 환경영향평가 절차: 시설, 전자기기, 서버 전력 소비 환경성 평가`
  },
  {
    id: 'doc-m-03',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_1',
    standards: ['ISO_45001'],
    code: 'QM-03',
    title: '안전보건경영시스템 매뉴얼 (OHSMS Manual)',
    category: '매뉴얼',
    version: 'v2.0',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-03-10',
    lastRevisionDate: '2024-04-30',
    expiryDate: '2024-06-15',
    dDay: 15,
    status: 'EXPIRING',
    docStatus: '개정 필요',
    validityStatus: 'CRITICAL',
    department: '안전보건팀',
    author: '박준호 대리',
    approver: '최지은 팀장',
    clauseNumber: 'Clause 5.4 근로자참여 및 6.1 위험성평가',
    path: '/안전보건시스템/01. 매뉴얼',
    commentsCount: 5,
    coverGradient: 'from-amber-600 via-orange-600 to-red-700',
    penaltyRisk: '중대재해처벌법 및 산안법 상 의무조항 위반 시 최대 1,000만원 과태료 및 입찰 참가 자격 정지',
    summary: 'ISO 45001:2018 기반 위험성 평가 및 산업재해 예방 매뉴얼',
    checklist: [
      { text: '상반기 정기 위험성평가 실시 및 공표', done: true },
      { text: '안전보건협의체 회의록 작성 및 보존', done: false },
      { text: '근로자 대표 안전보건 의견 수렴 기록', done: false }
    ],
    contentDraft: `[QM-03 안전보건경영 매뉴얼 v2.0]
- 목표: 무재해 사업장 유지 및 사고 위험 요인 사전 발굴
- 근로자 참여 및 협의 절차 확립`
  },
  {
    id: 'doc-m-04',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_1',
    standards: ['ISO_27001'],
    code: 'QM-04',
    title: '정보보호경영시스템 매뉴얼 (ISMS Manual)',
    category: '매뉴얼',
    version: 'v1.2',
    revisionNo: 'Rev. 1.2',
    approvalDate: '2024-02-28',
    lastRevisionDate: '2024-02-28',
    expiryDate: '2026-02-28',
    dDay: 530,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '정보보안팀',
    author: '이영진 팀장',
    approver: '김준호 총괄',
    clauseNumber: 'ISO 27001:2022 통제항목 전반',
    path: '/정보보호/01. 매뉴얼',
    commentsCount: 2,
    coverGradient: 'from-purple-600 via-violet-700 to-indigo-800',
    penaltyRisk: '개인정보 유출 사고 시 관련 매출액 3% 이하 과징금 및 ISMS 인증 취소',
    summary: 'ISO 27001:2022 개정 규격 반영, 클라우드 자산 보호 및 통제 관리 체계',
    checklist: [
      { text: '정보자산 식별 및 등급 분류 완료', done: true },
      { text: '취약점 진단 및 침투 테스트 보고서 갱신', done: true }
    ],
    contentDraft: `[QM-04 정보보안 매뉴얼 v1.2]
- 적용 범위: 고객 데이터베이스, SaaS 서비스 인프라, 전사 임직원 단말`
  },

  // 2. 절차서 (LEVEL_2)
  {
    id: 'doc-p-01',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_2',
    standards: ['ISO_9001', 'ISO_14001', 'ISO_27001'],
    code: 'QMS-P-001',
    title: '문서 및 데이터 관리 절차서',
    category: '절차서',
    version: 'v3.2',
    revisionNo: 'Rev. 3.2',
    approvalDate: '2024-05-20',
    lastRevisionDate: '2024-05-20',
    expiryDate: '2025-06-15',
    dDay: 38,
    status: 'EXPIRING',
    docStatus: '승인',
    validityStatus: 'WARNING',
    department: '품질경영팀',
    author: '홍길동',
    approver: '김철수',
    clauseNumber: '7.5 문서화된 정보 (Documented Information)',
    path: '/품질경영시스템/02. 절차서',
    commentsCount: 4,
    coverGradient: 'from-blue-700 via-sky-800 to-slate-800',
    penaltyRisk: '문서 개정 이력 누락 시 인증 심사 관찰(Observation) 또는 경부적합 처리',
    summary: '사내 규격 문서의 제정, 개정, 배포, 폐기 및 보존 기간을 통제하는 절차',
    checklist: [
      { text: '문서 제·개정 승인 권한 매트릭스 확인', done: true },
      { text: '구버전(폐기본) 오사용 방지 마킹 표기', done: true }
    ],
    contentDraft: `[QMS-P-001 문서관리 절차서]
1. 목적: 시스템의 모든 문서화된 정보를 식별, 작성, 검토, 승인하여 무결성을 유지함.
2. 보존 기한: 매뉴얼 영구, 절차서/지침서 개정 후 3년, 기록 3년 보존.`
  },
  {
    id: 'doc-p-02',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_2',
    standards: ['ISO_9001'],
    code: 'QMS-P-002',
    title: '내부심사 관리 절차서',
    category: '절차서',
    version: 'v2.2',
    revisionNo: 'Rev. 2.2',
    approvalDate: '2024-05-19',
    lastRevisionDate: '2024-05-18',
    expiryDate: '2025-06-15',
    dDay: 26,
    status: 'EXPIRING',
    docStatus: '검토 중',
    validityStatus: 'WARNING',
    department: '감사팀',
    author: '최지연 과장',
    approver: '박지훈 팀장',
    clauseNumber: '9.2 내부심사 (Internal Audit)',
    path: '/품질경영시스템/02. 절차서',
    commentsCount: 2,
    coverGradient: 'from-slate-700 via-indigo-900 to-blue-900',
    penaltyRisk: '정기 내부심사 미실시 시 ISO 정기 사후심사 수검 거부 및 인증 취소',
    summary: '연간 내부심사 계획 수립, 심사원 자격 부여, 부적합 시정조치 보고 절차',
    checklist: [
      { text: '2025년 상반기 내부심사원 적격성 평가 완료', done: true },
      { text: '독립적인 타 부서 심사팀 배정 확인', done: false }
    ],
    contentDraft: `[QMS-P-002 내부심사 절차서]
- 연간 최소 1회 전 부서 대상 내부심사 필수 실시
- 부적합 발견 시 14일 이내 시정조치 계획서 제출 의무`
  },
  {
    id: 'doc-p-03',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_2',
    standards: ['ISO_14001'],
    code: 'EMS-P-001',
    title: '환경영향 평가 절차서',
    category: '절차서',
    version: 'v4.0',
    revisionNo: 'Rev. 4.0',
    approvalDate: '2024-05-15',
    lastRevisionDate: '2024-05-15',
    expiryDate: '2026-05-15',
    dDay: 430,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '환경안전팀',
    author: '이영희',
    approver: '박원재',
    clauseNumber: '6.1.2 환경 측면',
    path: '/환경경영시스템/02. 절차서',
    commentsCount: 0,
    coverGradient: 'from-emerald-700 via-teal-800 to-green-900',
    penaltyRisk: '환경 배출물질 기준 초과 시 환경부 개선명령 및 과태료 부과',
    summary: '사업장 내 유의미한 환경 측면 식별 및 정량적 평가 절차',
    checklist: [{ text: '폐기물 및 전력 배출량 데이터 취합', done: true }],
    contentDraft: `[EMS-P-001 환경영향평가 절차서]\n- 정기평가: 매년 1회 / 수시평가: 공정 및 설비 변경 시`
  },
  {
    id: 'doc-p-04',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_2',
    standards: ['ISO_27001'],
    code: 'ISMS-P-001',
    title: '정보보안 정책 및 통제 절차서',
    category: '절차서',
    version: 'v2.3',
    revisionNo: 'Rev. 2.0',
    approvalDate: '2024-05-10',
    lastRevisionDate: '2024-05-17',
    expiryDate: '2024-07-01',
    dDay: 21,
    status: 'EXPIRING',
    docStatus: '승인',
    validityStatus: 'CRITICAL',
    department: '정보보안팀',
    author: '박민수',
    approver: '이성진',
    clauseNumber: 'A.5.1 정보보안 정책',
    path: '/정보보호/02. 절차서',
    commentsCount: 4,
    coverGradient: 'from-purple-800 via-indigo-900 to-slate-900',
    penaltyRisk: '보안 정책 미갱신 및 승인 지연 시 과태료 500만원 및 고객사 감사 탈락',
    summary: '전사 비밀번호 정책, 망분리, 접근 통제 및 계정 권한 회수 절차',
    checklist: [{ text: '퇴사자 계정 즉시 비활성화 로그 확인', done: true }],
    contentDraft: `[ISMS-P-001 정보보안 절차서]\n- 비밀번호 90일 주기 변경, 2단계 인증(MFA) 전사 의무화`
  },

  // 3. 지침서 (LEVEL_3)
  {
    id: 'doc-i-01',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_3',
    standards: ['ISO_9001'],
    code: 'QMS-I-17',
    title: '부적합품 식별 및 격리 처리 지침서',
    category: '지침서',
    version: 'v3.1',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-05-28',
    lastRevisionDate: '2024-05-15',
    expiryDate: '2025-05-28',
    dDay: 19,
    status: 'EXPIRING',
    docStatus: '승인',
    validityStatus: 'WARNING',
    department: '품질경영팀',
    author: '정희원 대리',
    approver: '김철수 차장',
    clauseNumber: '8.7 부적합 출력의 관리 (Control of Nonconforming Outputs)',
    path: '/품질경영시스템/03. 지침서',
    commentsCount: 1,
    coverGradient: 'from-cyan-700 via-blue-800 to-slate-800',
    penaltyRisk: '부적합품 혼입 출하 시 고객사 클레임 손해배상 및 거래 정지',
    summary: '불량 발생 시 붉은색 식별표 부착 및 격리 구역 이송 현장 작업 표준',
    checklist: [
      { text: '부적합품 전용 노란색/붉은색 라인 테이핑 구획 확인', done: true },
      { text: '폐기/재작업 판정서 3일 이내 작성 체계', done: false }
    ],
    contentDraft: `[QMS-I-17 부적합품 처리 지침]
- 발견 즉시 노란색 불량 태그 부착 및 QC 책임자 호출
- 재작업 시 원 공정 검사 기준과 동일하게 재검사 필수`
  },
  {
    id: 'doc-i-02',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_3',
    standards: ['ISO_9001'],
    code: 'WI-05',
    title: '내부감사 수행 세부 지침서',
    category: '지침서',
    version: 'v2.0',
    revisionNo: 'Rev. 2.0',
    approvalDate: '2024-05-01',
    lastRevisionDate: '2024-05-01',
    expiryDate: '2025-10-30',
    dDay: 350,
    status: 'READY',
    docStatus: '게시',
    validityStatus: 'NORMAL',
    department: '감사팀',
    author: '최지연 과장',
    approver: '박지훈 팀장',
    clauseNumber: '9.2 내부감사 실무',
    path: '/품질경영시스템/03. 지침서',
    commentsCount: 0,
    coverGradient: 'from-indigo-700 via-sky-800 to-slate-900',
    penaltyRisk: '심사원 편향 및 기록 미비 시 심사 무효화 처리',
    summary: '실제 심사원 인터뷰 요령, 샘플링 추출 기준 및 감사 보고서 양식 작성법',
    checklist: [{ text: '조항별 샘플링 질문 리스트 최신화', done: true }],
    contentDraft: `[WI-05 내부감사 지침]\n- 표본 추출: 최소 3개월 이상의 운영 기록 중 무작위 5건 추출`
  },
  {
    id: 'doc-i-03',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_3',
    standards: ['ISO_9001'],
    code: 'IS-G-001',
    title: '문서관리 실무 지침서',
    category: '지침서',
    version: 'v1.5',
    revisionNo: 'Rev. 1.5',
    approvalDate: '2024-04-25',
    lastRevisionDate: '2024-04-25',
    expiryDate: '2025-04-25',
    dDay: 360,
    status: 'READY',
    docStatus: '개정 필요',
    validityStatus: 'NORMAL',
    department: '품질경영팀',
    author: '김철수 차장',
    approver: '홍길동',
    clauseNumber: '7.5.2 작성 및 갱신',
    path: '/품질경영시스템/03. 지침서',
    commentsCount: 6,
    coverGradient: 'from-rose-600 via-pink-700 to-slate-800',
    penaltyRisk: '문서 번호 규칙 위반 시 시스템 동기화 오류 유발',
    summary: '표준 폰트(Pretendard), 여백, 문서코드 명명 규칙 가이드',
    checklist: [{ text: '신규 입사자 문서 서식 교육 완료', done: true }],
    contentDraft: `[IS-G-001 문서작성 지침서]\n- 머리글: 회사 로고 및 문서번호 필수 기재`
  },

  // 4. 기록/양식 (LEVEL_4)
  {
    id: 'doc-f-01',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_4',
    standards: ['ISO_9001', 'ISO_14001', 'ISO_27001'],
    code: 'QMS-F-001',
    title: '내부심사 점검 체크리스트',
    category: '기록/양식',
    version: 'v1.4',
    revisionNo: 'Rev. 2.0',
    approvalDate: '2024-05-08',
    lastRevisionDate: '2024-05-08',
    expiryDate: '2025-05-20',
    dDay: 11,
    status: 'EXPIRING',
    docStatus: '검토 중',
    validityStatus: 'CRITICAL',
    department: '감사팀',
    author: '최지연',
    approver: '박지훈',
    clauseNumber: '9.2 내부심사 증빙',
    path: '/품질경영시스템/04. 기록양식',
    commentsCount: 0,
    coverGradient: 'from-violet-600 via-purple-700 to-slate-800',
    penaltyRisk: '체크리스트 미작성 시 심사 미수행으로 간주되어 인증 갱신 불가',
    summary: 'ISO 조항별 183개 필수 요구사항 적합/부적합 판정 기록표',
    checklist: [
      { text: '조항 4~10 요구사항 전체 항목 수록 확인', done: true },
      { text: '부적합 발견 시 시정조치 요구서(CAR) 번호 연계', done: false }
    ],
    contentDraft: `[QMS-F-001 내부심사 체크리스트 서식]\n- 총 요구사항: 183개 / 적합(P), 부적합(F), 해당없음(N/A) 체크`
  },
  {
    id: 'doc-f-02',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_4',
    standards: ['ISO_9001'],
    code: 'IS-F-023',
    title: '교육훈련 기록부 및 이수증 서식',
    category: '기록/양식',
    version: 'v1.1',
    revisionNo: 'Rev. 1.1',
    approvalDate: '2024-05-21',
    lastRevisionDate: '2024-05-21',
    expiryDate: '2025-05-21',
    dDay: 365,
    status: 'READY',
    docStatus: '승인 대기',
    validityStatus: 'NORMAL',
    department: '인사팀',
    author: '이미란 사원',
    approver: '정다은 팀장',
    clauseNumber: '7.2 적격성 (Competence)',
    path: '/인사/04. 기록양식',
    commentsCount: 0,
    coverGradient: 'from-pink-600 via-rose-700 to-slate-800',
    penaltyRisk: '법정의무교육 미실시 시 1인당 최대 300만원 과태료',
    summary: '임직원 사내외 교육 참석자 서명부 및 효과성 평가 보고서',
    checklist: [{ text: '참석자 자필 서명 또는 전자서명 완료', done: true }],
    contentDraft: `[IS-F-023 교육훈련 기록서식]\n- 교육과정명, 일시, 강사, 참석자 명단, 교육 만족도 및 이해도 평가`
  },

  // 0. 인증서 원본 (만기 관리 핵심)
  {
    id: 'doc-cert-01',
    companyId: 'comp-1',
    hierarchyLevel: 'CERT',
    standards: ['ISO_9001'],
    code: 'CERT-ISO9001-2024',
    title: 'ISO 9001:2015 공식 인증서 원본',
    category: '인증서',
    version: 'v3.2',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-05-25',
    lastRevisionDate: '2024-05-25',
    expiryDate: '2025-05-25',
    dDay: 6,
    status: 'EXPIRING',
    docStatus: '위험',
    validityStatus: 'CRITICAL',
    department: '품질경영팀',
    author: '이영진',
    approver: '홍길동',
    clauseNumber: '공식 인증 인가서',
    path: '/인증서/2024',
    commentsCount: 8,
    coverGradient: 'from-rose-600 via-red-600 to-amber-700',
    penaltyRisk: '만기 시 조달청 다수공급자계약(MAS) 가점 박탈 및 현대/기아차 1차 협력사 벤더 등록 즉시 취소',
    summary: '품질경영시스템 국제표준 규격 인증서 (발급기관: KSA 한국표준협회 / 인증번호: IC-QMS-2024-0012)',
    checklist: [
      { text: '차기 사후심사(1년 주기) 신청서 접수', done: true },
      { text: '심사기관(KSA) 심사 일정 확정 및 비용 납부', done: false },
      { text: '사후심사용 문서 패키지 최종 검토', done: false }
    ],
    contentDraft: `[ISO 9001:2015 인증서 메타데이터]
- 인증등록번호: IC-QMS-2024-0012
- 인증기관: ISOEDU Certification
- 인증범위: 에듀테크 및 교육 관리 SaaS 솔루션의 기획, 개발 및 운영
- 유효기간: 2024-06-15 ~ 2025-06-15
- 사후관리 심사 예정일: 2025-06-15 (D-26)`
  },
  {
    id: 'doc-cert-02',
    companyId: 'comp-1',
    hierarchyLevel: 'CERT',
    standards: ['ISO_14001'],
    code: 'CERT-ISO14001-2024',
    title: 'ISO 14001:2015 환경경영시스템 인증서',
    category: '인증서',
    version: 'v2.0',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-05-28',
    lastRevisionDate: '2024-05-28',
    expiryDate: '2025-05-28',
    dDay: 9,
    status: 'EXPIRING',
    docStatus: '주의',
    validityStatus: 'WARNING',
    department: '환경경영팀',
    author: '박소연',
    approver: '김준호',
    clauseNumber: '공식 환경 인증서',
    path: '/인증서/2024',
    commentsCount: 3,
    coverGradient: 'from-amber-600 via-orange-600 to-amber-700',
    penaltyRisk: '만기 시 공공입찰 친환경 우수기업 가점 즉시 소멸',
    summary: '환경경영시스템 규격 인증서 (KSA 등록)',
    checklist: [
      { text: '인증 갱신 신청서 제출', done: true },
      { text: '환경 심사원 현장 실사 대비', done: false }
    ],
    contentDraft: `[ISO 14001 인증서] 유효기간: 2024-05-28 ~ 2025-05-28`
  },
  {
    id: 'doc-cert-03',
    companyId: 'comp-1',
    hierarchyLevel: 'CERT',
    standards: ['ISO_45001'],
    code: 'CERT-45001-2024',
    title: 'ISO 45001:2018 안전보건경영시스템 인증서',
    category: '인증서',
    version: 'v1.0',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-08-20',
    lastRevisionDate: '2024-08-20',
    expiryDate: '2025-08-20',
    dDay: 93,
    status: 'READY',
    docStatus: '정상',
    validityStatus: 'NORMAL',
    department: '안전보건팀',
    author: '최지은',
    approver: '김준호',
    clauseNumber: '공식 안전보건 인증서',
    path: '/인증서/2024',
    commentsCount: 1,
    coverGradient: 'from-emerald-600 via-teal-700 to-green-800',
    penaltyRisk: '중대재해 관련 공공 프로젝트 수주 배제',
    summary: '안전보건경영시스템 인증서',
    checklist: [{ text: '안전보건 경영방침 게시', done: true }],
    contentDraft: `[ISO 45001 인증서] 유효기간: 2024-08-20 ~ 2025-08-20`
  },
  {
    id: 'doc-cert-04',
    companyId: 'comp-1',
    hierarchyLevel: 'CERT',
    standards: ['VENTURE'],
    code: 'CERT-VENT-2024',
    title: '벤처기업확인서 (혁신성장유형)',
    category: '인증서',
    version: 'v1.0',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-06-01',
    lastRevisionDate: '2024-06-01',
    expiryDate: '2025-06-01',
    dDay: 30,
    status: 'EXPIRING',
    docStatus: '주의',
    validityStatus: 'WARNING',
    department: '경영기획팀',
    author: '박원재',
    approver: '김준호',
    clauseNumber: '벤처기업육성특별법',
    path: '/인증서/2024',
    commentsCount: 2,
    coverGradient: 'from-blue-600 via-indigo-700 to-slate-900',
    penaltyRisk: '만기 시 법인세 50% 감면 즉시 박탈 및 금융권 우대금리 취소',
    summary: '중진공 벤처기업확인기관 발급 혁신성장형 벤처기업 인증서',
    checklist: [{ text: '연구개발비 비율 5% 이상 유지', done: true }, { text: '3개년 사업계획서 갱신', done: false }],
    contentDraft: `[벤처기업 확인서] 유효기간: 2024-06-01 ~ 2025-06-01`
  },
  {
    id: 'doc-cert-05',
    companyId: 'comp-1',
    hierarchyLevel: 'CERT',
    standards: ['INNOBIZ'],
    code: 'CERT-INNO-2024',
    title: '이노비즈(Inno-Biz) 기술혁신형 중소기업 확인서',
    category: '인증서',
    version: 'v1.0',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-07-10',
    lastRevisionDate: '2024-07-10',
    expiryDate: '2027-07-10',
    dDay: 180,
    status: 'READY',
    docStatus: '정상',
    validityStatus: 'NORMAL',
    department: '기술연구소',
    author: '이영희',
    approver: '김준호',
    clauseNumber: '중소기업기술혁신촉진법',
    path: '/인증서/2024',
    commentsCount: 1,
    coverGradient: 'from-emerald-600 via-teal-700 to-slate-900',
    penaltyRisk: '기술평가 등급 하락 시 정책자금 한도 대폭 축소',
    summary: '중소벤처기업부 인증 기술혁신형 중소기업 확인서',
    checklist: [{ text: '기술혁신시스템 평가 700점 이상 유지', done: true }],
    contentDraft: `[이노비즈 확인서] 유효기간: 2024-07-10 ~ 2027-07-10`
  },
  {
    id: 'doc-cert-06',
    companyId: 'comp-1',
    hierarchyLevel: 'CERT',
    standards: ['KC'],
    code: 'CERT-KC-2024',
    title: '방송통신기자재등의 적합등록 필증 (KC 안전인증)',
    category: '인증서',
    version: 'v1.0',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-08-15',
    lastRevisionDate: '2024-08-15',
    expiryDate: '2026-08-15',
    dDay: 210,
    status: 'READY',
    docStatus: '정상',
    validityStatus: 'NORMAL',
    department: '품질개발팀',
    author: '정현우',
    approver: '김철수',
    clauseNumber: '전파법 제58조의2',
    path: '/인증서/2024',
    commentsCount: 0,
    coverGradient: 'from-cyan-600 via-blue-700 to-slate-900',
    penaltyRisk: 'KC 미인증 기기 유통 시 3년 이하 징역 또는 3천만원 이하 벌금',
    summary: '국립전파연구원 전파인증 적합등록 필증',
    checklist: [{ text: '공인시험성적서 보관', done: true }],
    contentDraft: `[KC 적합등록 필증] 등록번호: R-R-ISO-2024-0091`
  },
  {
    id: 'doc-m-05',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_1',
    standards: ['LABOR'],
    code: 'POL-HR-01',
    title: '표준 취업규칙 및 인사노무 관리규정',
    category: '매뉴얼',
    version: 'v2.0',
    revisionNo: 'Rev. 2.0',
    approvalDate: '2024-05-10',
    lastRevisionDate: '2024-05-10',
    expiryDate: '2026-05-10',
    dDay: 360,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '인사총무팀',
    author: '강예리',
    approver: '김준호',
    clauseNumber: '근로기준법 제93조',
    path: '/노무인사/01. 매뉴얼',
    commentsCount: 3,
    coverGradient: 'from-indigo-600 to-blue-800',
    penaltyRisk: '상시 근로자 10인 이상 취업규칙 노동청 미신고 시 과태료 500만원',
    summary: '근로기준법 최신 개정 반영 복무규정, 연차유급휴가, 직장내 괴롭힘 예방',
    checklist: [{ text: '근로자 과반수 동의서 첨부', done: true }, { text: '관할 고용노동청 신고필증 수령', done: true }],
    contentDraft: `# 표준 취업규칙 전문\n제1조(목적) 본 규칙은 임직원의 근로조건 및 복무규율을 정함을 목적으로 한다.`
  },
  {
    id: 'doc-m-06',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_1',
    standards: ['CORP'],
    code: 'GOV-ART-01',
    title: '주식회사 표준 정관 및 임원보수 규정',
    category: '매뉴얼',
    version: 'v3.0',
    revisionNo: 'Rev. 3.0',
    approvalDate: '2024-03-25',
    lastRevisionDate: '2024-03-25',
    expiryDate: '2027-03-25',
    dDay: 480,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '경영기획팀',
    author: '박원재',
    approver: '홍길동',
    clauseNumber: '상법 제289조',
    path: '/법무정관/01. 매뉴얼',
    commentsCount: 2,
    coverGradient: 'from-slate-700 to-slate-950',
    penaltyRisk: '임원 퇴직금 규정 부재 시 세무조사 손금불산입 및 법인세 추징',
    summary: '정기주총 승인 표준 정관, 주식매수선택권(스톡옵션) 및 지분 변동 규칙',
    checklist: [{ text: '공증인 정관 인증 완료', done: true }],
    contentDraft: `# 주식회사 정관\n제1조(상호) 본 회사는 주식회사 아이소에듀라 칭한다.`
  },
  {
    id: 'doc-p-05',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_2',
    standards: ['FUND'],
    code: 'FIN-P-01',
    title: '정책자금 융자 심사 및 결산 재무제표 관리 절차서',
    category: '절차서',
    version: 'v1.5',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-05-15',
    lastRevisionDate: '2024-05-15',
    expiryDate: '2025-05-15',
    dDay: 15,
    status: 'EXPIRING',
    docStatus: '주의',
    validityStatus: 'WARNING',
    department: '재무회계팀',
    author: '이서연',
    approver: '홍길동',
    clauseNumber: '기보/신보 심사기준',
    path: '/재무자금/02. 절차서',
    commentsCount: 4,
    coverGradient: 'from-amber-700 to-yellow-900',
    penaltyRisk: '부채비율 관리 실패 및 가수금 미정리 시 보증서 발급 거절',
    summary: '기술보증기금/신용보증기금/중진공 운전자금 신청 및 재무건전성 가이드',
    checklist: [{ text: '표준재무제표증명원 발급', done: true }, { text: '국세/지방세 완납증명서 확인', done: true }],
    contentDraft: `# 정책자금 결산 관리 절차서\n매년 결산 전 부채비율 200% 이하 관리 및 가지급금 정리 필수.`
  },
  {
    id: 'doc-p-06',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_2',
    standards: ['RND'],
    code: 'LAB-P-01',
    title: '기업부설연구소 인력 변경신고 및 연구개발비 관리 절차서',
    category: '절차서',
    version: 'v2.0',
    revisionNo: 'Rev. 2.0',
    approvalDate: '2024-05-18',
    lastRevisionDate: '2024-05-18',
    expiryDate: '2025-05-25',
    dDay: 5,
    status: 'EXPIRING',
    docStatus: '위험',
    validityStatus: 'CRITICAL',
    department: '기술연구소',
    author: '이영희',
    approver: '김준호',
    clauseNumber: '기초연구진흥법 시행령',
    path: '/연구소R&D/02. 절차서',
    commentsCount: 5,
    coverGradient: 'from-rose-700 to-red-900',
    penaltyRisk: '연구원 퇴사/전입 후 14일 이내 변경신고 누락 시 연구소 직권취소 및 세제감면 추징',
    summary: 'KOITA 연구소 전담요원 자격 유지, 연구개발비 비목별 집행 관리',
    checklist: [{ text: '연구원 4대보험 가입자명부 대조', done: true }, { text: 'KOITA 변경신고 14일 이내 접수', done: false }],
    contentDraft: `# 연구소 변경신고 절차서\n연구전담요원 변동 발생 시 14일 이내 온라인(KOITA) 신고 필수.`
  },
  {
    id: 'doc-p-07',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_2',
    standards: ['SUPPORT'],
    code: 'GOV-P-02',
    title: '정부지원사업(초창패/창도패/바우처) 사업비 집행 및 정산 절차서',
    category: '절차서',
    version: 'v1.2',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-05-20',
    lastRevisionDate: '2024-05-20',
    expiryDate: '2025-06-30',
    dDay: 35,
    status: 'EXPIRING',
    docStatus: '검토 중',
    validityStatus: 'WARNING',
    department: '전략기획팀',
    author: '박원재',
    approver: '김준호',
    clauseNumber: '창업진흥원 관리지침',
    path: '/정부지원사업/02. 절차서',
    commentsCount: 2,
    coverGradient: 'from-emerald-700 to-teal-900',
    penaltyRisk: '사업비 부정 집행 및 증빙 미비 시 정부지원금 환수 및 제재부가금 부과',
    summary: '케이스타트업/e나라도움 전담기관 전자세금계산서 정산 및 진도보고서 작성',
    checklist: [{ text: '전용 사업비 카드 영수증 편철', done: true }, { text: '비교견적서 및 결과보고서 첨부', done: true }],
    contentDraft: `# 정부지원사업 정산 절차서\n모든 집행은 협약 체결된 비목/세목 내에서만 지출 승인.`
  },
  {
    id: 'doc-i-04',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_3',
    standards: ['TAX'],
    code: 'TAX-I-01',
    title: '연구인력개발비 세액공제 및 벤처 세제감면 증빙 지침서',
    category: '지침서',
    version: 'v1.0',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-04-30',
    lastRevisionDate: '2024-04-30',
    expiryDate: '2026-04-30',
    dDay: 365,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '재무회계팀',
    author: '이서연',
    approver: '김준호',
    clauseNumber: '조세특례제한법 제10조',
    path: '/세무회계/03. 지침서',
    commentsCount: 1,
    coverGradient: 'from-blue-700 to-indigo-900',
    penaltyRisk: '연구노트 등 증빙 불충분 시 세액공제 전액 부인 및 과소신고가산세(20%)',
    summary: '국세청 R&D 세액공제 사전심사 대응 연구보고서 및 타임시트 작성 요령',
    checklist: [{ text: '월별 연구개발 활동 타임시트 작성', done: true }],
    contentDraft: `# R&D 세액공제 지침\n연구원 급여 대장과 연구노트를 상호 대조하여 공제 대상 인건비 산출.`
  },
  {
    id: 'doc-i-05',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_3',
    standards: ['LABOR'],
    code: 'HR-I-02',
    title: '청년일자리도약장려금 등 고용지원금 신청 실무 지침서',
    category: '지침서',
    version: 'v1.1',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-05-12',
    lastRevisionDate: '2024-05-12',
    expiryDate: '2025-05-31',
    dDay: 20,
    status: 'EXPIRING',
    docStatus: '승인',
    validityStatus: 'WARNING',
    department: '인사총무팀',
    author: '강예리',
    approver: '김준호',
    clauseNumber: '고용보험법',
    path: '/고용지원금/03. 지침서',
    commentsCount: 2,
    coverGradient: 'from-amber-600 to-orange-800',
    penaltyRisk: '신청 기한 도과 시 지원금(최대 1,200만원) 수급권 자동 소멸',
    summary: '정규직 채용 후 6개월 근속 요건 확인 및 분기별 지원금 청구 가이드',
    checklist: [{ text: '급여이체확인증 및 임금대장 편철', done: true }],
    contentDraft: `# 고용지원금 신청 지침\n채용 후 6개월 도래 시점부터 3개월 이내 온라인 신청 필수.`
  },
  {
    id: 'doc-f-03',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_4',
    standards: ['SUPPORT'],
    code: 'PSST-F-01',
    title: '초기창업패키지(초창패) PSST 사업계획서 표준 서식',
    category: '기록/양식',
    version: 'v2.0',
    revisionNo: 'Rev. 2.0',
    approvalDate: '2024-05-10',
    lastRevisionDate: '2024-05-10',
    expiryDate: '2025-06-15',
    dDay: 25,
    status: 'EXPIRING',
    docStatus: '검토 중',
    validityStatus: 'WARNING',
    department: '전략기획팀',
    author: '박원재',
    approver: '김준호',
    clauseNumber: '중소벤처기업부 공고양식',
    path: '/정부지원사업/04. 기록양식',
    commentsCount: 6,
    coverGradient: 'from-purple-600 to-pink-800',
    penaltyRisk: 'PSST 작성 요령 미준수 시 서면평가 기본 과락 탈락',
    summary: '문제인식(P) - 실현가능성(S) - 성장전략(S) - 팀구성(T) 표준 템플릿',
    checklist: [{ text: '차별점 및 시장 규모 정량 데이터 수록', done: true }, { text: '참여인력 이력서 첨부', done: true }],
    contentDraft: `# PSST 사업계획서 서식\n1. 문제인식: 기존 시장의 페인포인트 분석 및 해결책 도출.`
  },
  {
    id: 'doc-f-04',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_4',
    standards: ['CORP'],
    code: 'SH-F-01',
    title: '주주명부 및 주식양수도계약서 표준 서식',
    category: '기록/양식',
    version: 'v1.0',
    revisionNo: 'Rev. 1.0',
    approvalDate: '2024-03-30',
    lastRevisionDate: '2024-03-30',
    expiryDate: '2026-03-30',
    dDay: 300,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '경영기획팀',
    author: '박원재',
    approver: '홍길동',
    clauseNumber: '상법 제352조',
    path: '/법무주식/04. 기록양식',
    commentsCount: 1,
    coverGradient: 'from-slate-700 to-indigo-950',
    penaltyRisk: '주주명부 미비 시 의결권 행사 무효 및 지분 분쟁 발생',
    summary: '실시간 지분율, 주식수, 주권번호 및 명의개서 일자 관리 양식',
    checklist: [{ text: '증권거래세 신고 내역 대조', done: true }],
    contentDraft: `# 주주명부 서식\n성명, 주민등록번호, 주소, 소유주식수, 지분율(%) 기재.`
  },
  {
    id: 'doc-f-05',
    companyId: 'comp-1',
    hierarchyLevel: 'LEVEL_4',
    standards: ['RND'],
    code: 'LAB-F-01',
    title: '기업부설연구소 연구개발활동조사표 및 연구노트 서식',
    category: '기록/양식',
    version: 'v2.1',
    revisionNo: 'Rev. 2.0',
    approvalDate: '2024-05-01',
    lastRevisionDate: '2024-05-01',
    expiryDate: '2025-05-31',
    dDay: 20,
    status: 'EXPIRING',
    docStatus: '검토 중',
    validityStatus: 'WARNING',
    department: '기술연구소',
    author: '이영희',
    approver: '김준호',
    clauseNumber: '연구노트 지침(과학기술정보통신부 훈령)',
    path: '/연구소R&D/04. 기록양식',
    commentsCount: 2,
    coverGradient: 'from-emerald-600 to-blue-900',
    penaltyRisk: '연구노트 미작성 시 특허 출원 우선권 입증 불가 및 R&D 세액공제 취소',
    summary: '날짜별 연구 내용, 실험 결과, 참여자 서명 및 연구책임자 확인 서식',
    checklist: [{ text: '주간 단위 연구노트 서명 날인', done: true }],
    contentDraft: `# 연구개발활동 보고 서식\n과제명, 연구원, 실험 일자, 실험 목적, 결과 및 향후 계획.`
  },

  // comp-2 (에듀캠퍼스(주) - ISO 14001 환경경영)
  {
    id: 'doc-comp2-01',
    companyId: 'comp-2',
    hierarchyLevel: 'CERT',
    standards: ['ISO_14001'],
    code: 'CERT-14001',
    title: 'ISO 14001:2015 환경경영시스템 인증서 원본',
    category: '인증서',
    version: 'v1.0',
    approvalDate: '2024-06-20',
    expiryDate: '2027-06-19',
    dDay: 31,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '환경경영팀',
    author: '이민정 대표',
    approver: '김철수 심사원',
    clauseNumber: '인증서 원본',
    path: '/환경경영시스템/00. 인증서',
    summary: '에듀캠퍼스(주) 친환경 교육장 운영 및 그린 서비스 ISO 14001 인증서',
    contentDraft: `# ISO 14001:2015 환경경영시스템 인증서\n\n사업장: 에듀캠퍼스(주)\n인증번호: IC-EMS-2024-0091\n인증범위: 기업 직무 교육 및 HR 컨설팅 서비스\n유효기간: 2024-06-20 ~ 2027-06-19`
  },
  {
    id: 'doc-comp2-02',
    companyId: 'comp-2',
    hierarchyLevel: 'LEVEL_1',
    standards: ['ISO_14001'],
    code: 'EM-01',
    title: '환경경영시스템 적용범위서 및 환경매뉴얼',
    category: '매뉴얼',
    version: 'v1.2',
    approvalDate: '2024-06-25',
    expiryDate: '2026-12-31',
    dDay: 300,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '환경경영팀',
    author: '이민정 대표',
    approver: '이민정 대표',
    clauseNumber: 'Clause 4.3',
    path: '/환경경영시스템/01. 매뉴얼',
    summary: '에듀캠퍼스(주) 교육장 에너지 절감 및 디지털 페이퍼리스 환경경영 방침',
    contentDraft: `# EM-01 에듀캠퍼스 환경경영 매뉴얼\n\n제1조(목적) 본 매뉴얼은 ISO 14001:2015 요구사항에 따른 환경경영시스템을 수립한다.\n제2조(적용범위) 에듀캠퍼스 판교 교육장 및 온라인 교육 전반에 적용한다.`
  },
  {
    id: 'doc-comp2-03',
    companyId: 'comp-2',
    hierarchyLevel: 'LEVEL_1',
    standards: ['ISO_14001'],
    code: 'EP-01',
    title: '환경방침 선언서',
    category: '매뉴얼',
    version: 'v1.0',
    approvalDate: '2024-07-01',
    expiryDate: '2026-12-31',
    dDay: 300,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '환경경영팀',
    author: '이민정 대표',
    approver: '이민정 대표',
    clauseNumber: 'Clause 5.2',
    path: '/환경경영시스템/01. 매뉴얼',
    summary: '탄소배출 저감, 페이퍼리스 교육 실천 환경방침',
    contentDraft: `# EP-01 에듀캠퍼스 환경방침\n\n1. 탄소배출 최소화 교육장 운영\n2. 100% 디지털 교재 배포를 통한 페이퍼리스 실천\n3. 환경 법규 100% 준수`
  },
  {
    id: 'doc-comp2-04',
    companyId: 'comp-2',
    hierarchyLevel: 'LEVEL_2',
    standards: ['ISO_14001'],
    code: 'EMP-01',
    title: '환경영향평가 및 리스크 관리 절차서',
    category: '절차서',
    version: 'v1.0',
    approvalDate: '2024-07-10',
    expiryDate: '2026-12-31',
    dDay: 300,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '환경경영팀',
    author: '최환경',
    approver: '이민정 대표',
    clauseNumber: 'Clause 6.1.2',
    path: '/환경경영시스템/02. 절차서',
    summary: '전력, 폐기물, 용수 사용에 따른 환경측면 식별 및 평가 기준',
    contentDraft: `# EMP-01 환경측면 식별 및 환경영향평가 절차서\n\n1. 목적: 사내 활동이 환경에 미치는 직간접 영향을 평가하여 중점 관리항목을 선정한다.`
  },

  // comp-3 (스마트러닝 솔루션즈 - ISO 27001 정보보안)
  {
    id: 'doc-comp3-01',
    companyId: 'comp-3',
    hierarchyLevel: 'LEVEL_1',
    standards: ['ISO_27001'],
    code: 'ISP-01',
    title: '정보보호 정책서 및 정보보호경영시스템(ISMS) 적용범위서',
    category: '매뉴얼',
    version: 'v1.0',
    approvalDate: '2024-08-01',
    expiryDate: '2026-12-31',
    dDay: 300,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '보안팀',
    author: '박상현 대표',
    approver: '박상현 대표',
    clauseNumber: 'Clause 4.3 / 5.2',
    path: '/정보보안/01. 매뉴얼',
    summary: '스마트러닝 코딩 교육 플랫폼 클라우드 인프라 및 수강생 개인정보 보호 정책',
    contentDraft: `# ISP-01 정보보호 기본 정책서\n\n1. 목적: 코딩 교육 플랫폼 클라우드 인프라와 학습자 데이터를 안전하게 보호한다.\n2. 범위: AWS 클라우드 인프라 및 웹 서비스 전반`
  },
  {
    id: 'doc-comp3-02',
    companyId: 'comp-3',
    hierarchyLevel: 'LEVEL_2',
    standards: ['ISO_27001'],
    code: 'SoA-01',
    title: '정보보호 통제항목 적용성보고서 (Statement of Applicability)',
    category: '절차서',
    version: 'v1.0',
    approvalDate: '2024-08-15',
    expiryDate: '2026-12-31',
    dDay: 300,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: '보안팀',
    author: '최보안',
    approver: '박상현 대표',
    clauseNumber: 'Clause 6.1.3',
    path: '/정보보안/02. 절차서',
    summary: 'ISO 27001:2022 부속서 A 93개 통제항목 적용/제외 사유서',
    contentDraft: `# SoA-01 적용성보고서\n\nISO 27001:2022 Annex A 93개 보안통제 항목별 적용 여부 및 증빙 문서 정의.`
  },

  // comp-bio ((주)메디바이오텍 - ISO 13485 의료기기)
  {
    id: 'doc-compbio-01',
    companyId: 'comp-bio',
    hierarchyLevel: 'LEVEL_1',
    standards: ['ISO_13485'],
    code: 'MD-QM-01',
    title: '의료기기 품질경영 매뉴얼 및 기술문서(TCF/DHF)',
    category: '매뉴얼',
    version: 'v1.0',
    approvalDate: '2024-09-01',
    expiryDate: '2026-12-31',
    dDay: 300,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: 'RA/QA팀',
    author: '정승호 대표',
    approver: '정승호 대표',
    clauseNumber: 'Clause 4.2.2 & 4.2.3',
    path: '/의료기기품질/01. 매뉴얼',
    summary: '체외진단 시약 제조소 품질시스템 및 설계이력파일(DHF) 총괄 규정',
    contentDraft: `# MD-QM-01 의료기기 품질경영 매뉴얼\n\n1. 목적: ISO 13485:2016 및 CE MDR 적합성 보장\n2. 품목: 체외진단용 분자검사 키트`
  },
  {
    id: 'doc-compbio-02',
    companyId: 'comp-bio',
    hierarchyLevel: 'LEVEL_2',
    standards: ['ISO_13485'],
    code: 'MD-P-14971',
    title: '의료기기 위험관리(ISO 14971) 절차서',
    category: '절차서',
    version: 'v1.0',
    approvalDate: '2024-09-10',
    expiryDate: '2026-12-31',
    dDay: 300,
    status: 'READY',
    docStatus: '승인',
    validityStatus: 'NORMAL',
    department: 'RA/QA팀',
    author: '강연구',
    approver: '정승호 대표',
    clauseNumber: 'Clause 7.1',
    path: '/의료기기품질/02. 절차서',
    summary: '전수명주기 위험분석, 위험통제(Risk Control) 및 잔여위험 평가 기준',
    contentDraft: `# MD-P-14971 위험관리 절차서\n\nISO 14971:2019 규격에 따른 위험 분석, 평가 및 위험-이득 분석 절차.`
  }
];

// Rich content mapping & domain tagging
export const SEED_DOCUMENTS = BASE_SEED_DOCUMENTS.map(doc => {
  const rich = RICH_DOCUMENT_CONTENTS[doc.code];
  if (!rich) return doc;
  return {
    ...doc,
    ...rich,
    id: doc.id,
    code: doc.code,
    companyId: doc.companyId,
    contentDraft: rich.contentDraft || doc.contentDraft,
    summary: rich.summary || doc.summary,
    penaltyRisk: rich.penaltyRisk || doc.penaltyRisk,
    consultingCategory: rich.consultingCategory || doc.consultingCategory || 'ISO_STANDARDS',
    consultingDomain: rich.consultingDomain || doc.consultingDomain || 'ISO 규격 인증',
  };
});

// 통합 검색용 목 데이터 (시안 13번 매핑)
export const SEARCH_CLAUSE_RESULTS = [
  { clauseId: '4.2.1', title: '이해관계자의 요구사항 이해', docTitle: 'QM-01 품질경영 매뉴얼', page: 'p.12', snippet: '...조직은 이해관계자의 요구사항을 이해하고 이를 품질경영시스템에 반영하여야 한다...' },
  { clauseId: '4.2.1-B', title: '조직의 이해', docTitle: 'QM-01 품질경영 매뉴얼', page: 'p.13', snippet: '...조직은 조직의 목적 달성에 영향을 미치는 내부 및 외부 이슈를 결정하여야 한다...' },
  { clauseId: '6.2.1', title: '품질목표 및 달성계획 수립', docTitle: 'QM-01-02 품질목표', page: 'p.8', snippet: '...조직은 관련 기능 및 수준에서 품질목표를 수립하고 관리하여야 한다...' },
  { clauseId: '7.5.1', title: '문서화된 정보 (일반)', docTitle: 'QMS-P-001 문서관리 절차서', page: 'p.3', snippet: '...품질경영시스템은 본 표준에서 요구하는 문서화된 정보 및 효과성을 위해 결정한 문서를 포함...' },
  { clauseId: '9.2.1', title: '내부심사 계획 및 실시', docTitle: 'QMS-P-002 내부심사 절차서', page: 'p.5', snippet: '...조직은 계획된 주기로 내부심사를 실시하여 품질경영시스템이 요구사항에 적합한지 확인...' }
];

// 시연용 4대 프리셋 시나리오
export const DEMO_SCENARIOS = [
  {
    id: 'scenario-1',
    tag: '제조업 / 공공조달',
    title: '제조업 3년 차, 조달청 MAS 및 공공입찰 대비 ISO 9001/14001',
    prompt: '정밀 금속가공 제조업 3년 차 기업입니다. 하반기 조달청 다수공급자계약(MAS) 등록과 현대차 1차 벤더 협력사 등록을 위해 ISO 9001과 ISO 14001 인증을 급하게 준비해야 합니다. 어떤 문서 체계가 필수적으로 필요하고 즉시 구성할 수 있나요?',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-200',
    responseAnalysis: `**[기업 현황 진단]**
- **대상 업종:** 정밀가공/기계 제조업 (업력 3년 차)
- **주요 목적:** 조달청 나라장터 MAS 가점 확보, 대기업 협력사 등록 요건 충족
- **필요 규격:** **ISO 9001 (품질)** 및 **ISO 14001 (환경)** 복합 인증 체계

**[진단 결과 및 전략]**
공공입찰 심사관 및 벤더 등록 평가위원은 단순 인증서뿐만 아니라 **'문서 및 기록관리(7.5)', '부적합품 관리(8.7)', '설비 보전 및 검교정(7.1.5)'** 관련 실질 절차서와 최근 3개월간의 가동 기록 증빙을 가장 엄격하게 검증합니다.

지금 바로 적용 가능한 **[제조업 특화 ISO 9001/14001 필수 5종 패키지]**를 구성했습니다.`,
    recommendedDocs: [
      {
        companyId: 'comp-1',
        certificationCode: 'ISO_9001',
        hierarchyLevel: 'LEVEL_1',
        clauseNumber: 'Clause 4~10',
        code: 'QM-MFG-01',
        title: '정밀제조 품질경영 매뉴얼 (통합형)',
        status: 'READY',
        expiryDate: '2027-09-30',
        dDay: 387,
        penaltyRisk: '매뉴얼 누락 시 조달청 PQ 적격심사 품질경영 부문 감점 (1.5점 감점)',
        summary: '제조업 맞춤형 10대 조항 총괄 품질 매뉴얼 (설비관리 및 작업표준 포함)',
        checklist: [
          { text: '품질경영 방침 수립 및 서명', done: true },
          { text: '조직도 및 직무권한표 개정', done: true },
        ],
        contentDraft: `# 정밀제조 품질경영 매뉴얼\n본 매뉴얼은 부품 가공의 정밀성과 친환경 공정 준수를 기본으로 조달청 품질 기준을 100% 충족하도록 작성됨.`
      },
      {
        companyId: 'comp-1',
        certificationCode: 'ISO_9001',
        hierarchyLevel: 'LEVEL_2',
        clauseNumber: 'Clause 8.5.1',
        code: 'QP-MFG-02',
        title: '제조공정 관리 및 설비예방보전 절차서',
        status: 'READY',
        expiryDate: '2027-09-30',
        dDay: 387,
        penaltyRisk: '설비 점검 이력 미비 시 제조물배상책임(PL) 분쟁 및 조달 하자보수 제재',
        summary: 'CNC 선반, 머시닝센터 등 주요 생산설비의 일일/월간 점검 및 공정 모니터링 절차',
        checklist: [
          { text: '주요 설비 이력카드 작성', done: true },
          { text: '예방보전 점검 주기표 설정', done: true },
        ],
        contentDraft: `# 제조공정 관리 절차서\n설비 고장으로 인한 납기 지연 방지를 위해 매월 1회 정기 분해점검을 의무화한다.`
      },
      {
        companyId: 'comp-1',
        certificationCode: 'ISO_9001',
        hierarchyLevel: 'LEVEL_2',
        clauseNumber: 'Clause 8.7',
        code: 'QP-MFG-04',
        title: '부적합품 식별 및 격리/폐기 절차서',
        status: 'READY',
        expiryDate: '2027-09-30',
        dDay: 387,
        penaltyRisk: '불량품 혼입 출하 시 조달청 부정당업자 지정 및 6개월간 입찰 참가 자격 제한',
        summary: '가공 불량 발생 시 붉은색 식별표 부착 및 불합격 보관장 격리 절차',
        checklist: [
          { text: '부적합품 적치장소 펜스 및 표지판 설치', done: true },
          { text: '폐기 승인 전결 규정 마련', done: true },
        ],
        contentDraft: `# 부적합품 관리 절차서\n가공 공차 초과 제품은 즉시 '부적합 식별표'를 부착하고 24시간 이내에 격리장소로 이동한다.`
      },
      {
        companyId: 'comp-1',
        certificationCode: 'ISO_14001',
        hierarchyLevel: 'LEVEL_2',
        clauseNumber: 'Clause 6.1.2',
        code: 'EP-ENV-01',
        title: '환경측면 파악 및 유해물질 관리 절차서',
        status: 'READY',
        expiryDate: '2027-09-30',
        dDay: 387,
        penaltyRisk: '절삭유/지정폐기물 무단 배출 적발 시 최대 5년 이하 징역 또는 5천만원 이하 벌금',
        summary: '금속가공 절삭유, 세척용제, 칩 폐기물 배출 관리 및 환경영향 평가 기준',
        checklist: [
          { text: 'MSDS(물질안전보건자료) 현장 비치', done: true },
          { text: '지정폐기물 위탁처리 계약서 연계', done: true },
        ],
        contentDraft: `# 환경측면 파악 절차서\n폐유 및 금속칩은 환경부 허가 위탁업체를 통해 100% 인계하며 '올바로 시스템'에 등록한다.`
      },
      {
        companyId: 'comp-1',
        certificationCode: 'ISO_9001',
        hierarchyLevel: 'LEVEL_4',
        clauseNumber: 'Clause 7.1.5',
        code: 'FORM-CAL-01',
        title: '계측기/측정장비 검교정 관리대장',
        status: 'READY',
        expiryDate: '2027-03-31',
        dDay: 204,
        penaltyRisk: '검교정 만료 계측기 사용 적발 시 심사 즉시 불합격 및 성적서 무효 처리',
        summary: '버니어캘리퍼스, 마이크로미터, 하이트게이지 등 국가공인 검교정 주기 관리 양식',
        checklist: [
          { text: '한국인정기구(KOLAS) 성적서 번호 기재', done: true },
          { text: '차기 교정 만기일 라벨 부착', done: true },
        ],
        contentDraft: `# 계측기 관리대장 양식\n기기명, 일련번호, 관리번호, 교정일자, 차기교정일, 교정기관, 판정결과 기록.`
      }
    ]
  },
  {
    id: 'scenario-2',
    tag: 'IT/SaaS / 보안·투자',
    title: '클라우드 SaaS 기업, 투자 유치 및 데이터 보안을 위한 벤처인증 + ISO 27001',
    prompt: '저희는 B2B 엔터프라이즈 SaaS 소프트웨어를 개발하는 2년 차 스타트업입니다. 시리즈 A 투자 유치 및 금융권 고객사 납품을 위해 벤처기업인증(혁신성장형)과 ISO 27001(정보보호경영) 인증이 시급합니다. 어떤 서류들이 필요한가요?',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-200',
    responseAnalysis: `**[기업 현황 진단]**
- **대상 업종:** B2B SaaS / 클라우드 소프트웨어 (업력 2년 차)
- **주요 목적:** 시리즈 A 투자사 실사(DD), 금융/대기업 고객사 보안 평가 통과
- **필요 규격:** **벤처기업인증 (혁신성장형)** 및 **ISO/IEC 27001 (정보보호)**

**[진단 결과 및 전략]**
SaaS 기업의 경우 벤처인증에서는 **'기술보증기금/전문기관 평가 지표(특허 보유, R&D 역량)'**가 핵심이며, ISO 27001에서는 **'클라우드 접근제어(A.9)', '개인정보 암호화(A.10)', '침해사고 대응 절차(A.16)'**가 필수 검증 대상입니다.

투자 실사 및 보안 감사에 즉시 제출할 수 있는 **[SaaS/IT 특화 필수 5종 세트]**를 준비했습니다.`,
    recommendedDocs: [
      {
        companyId: 'comp-1',
        certificationCode: 'ISO_27001',
        hierarchyLevel: 'LEVEL_1',
        clauseNumber: 'Clause 4~10',
        code: 'ISMS-M-01',
        title: '클라우드 정보보호경영 매뉴얼 (ISO 27001:2022)',
        status: 'READY',
        expiryDate: '2027-10-31',
        dDay: 418,
        penaltyRisk: '금융권 납품 시 보안 감사 미달로 계약 파기 및 위약금 발생',
        summary: 'AWS/GCP 클라우드 인프라 기반 SaaS 서비스 정보보호 최고방침 및 ISMS 운영규정',
        checklist: [
          { text: '정보보호 조직 및 CISO/CPO 지정 확인', done: true },
          { text: '정보보호 정책서 전 임직원 서약 완료', done: true },
        ],
        contentDraft: `# 정보보호 매뉴얼\n본 매뉴얼은 클라우드 환경의 데이터 암호화, 접근 통제 및 제3자 외주 개발자 보안 통제를 규정한다.`
      },
      {
        companyId: 'comp-1',
        certificationCode: 'ISO_27001',
        hierarchyLevel: 'LEVEL_2',
        clauseNumber: 'Clause A.9.2',
        code: 'SOP-SEC-03',
        title: '사용자 접근통제 및 계정 권한 관리 절차서',
        status: 'READY',
        expiryDate: '2027-10-31',
        dDay: 418,
        penaltyRisk: '퇴사자 계정 미회수로 인한 데이터 유출 시 5억원 이하 과징금 (개인정보보호법)',
        summary: 'DB 및 관리자 콘솔 접근 권한 신청, 승인, 90일 주기 권한 검토 및 퇴사자 즉시 회수 절차',
        checklist: [
          { text: '2단계 인증(MFA/2FA) 전사 강제 적용', done: true },
          { text: '분기별 휴면 계정 및 불필요 권한 회수 로그 확인', done: true },
        ],
        contentDraft: `# 계정 권한 관리 절차서\n모든 운영 DB 접근은 승인된 IP에서만 허용하며, 퇴사 처리 시 1시간 이내에 모든 사내 시스템 권한을 회수한다.`
      }
    ]
  },
  {
    id: 'scenario-3',
    tag: '식품/바이오 / 위생·안전',
    title: '식품 제조가공 기업, 대형마트 납품을 위한 스마트 HACCP 및 ISO 22000',
    prompt: '가공식품을 제조하는 기업입니다. 이번에 컬리와 이마트 납품 심사가 잡혀있는데, 스마트 HACCP 및 ISO 22000 인증 문서 세트가 시급합니다.',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    responseAnalysis: `**[기업 현황 진단]**
- **대상 업종:** 식품 제조가공 및 소스류 HMR
- **주요 목적:** 대형 유통채널(이마트, 마켓컬리) 벤더 입점 심사 통과
- **필요 규격:** **스마트 HACCP** 및 **ISO 22000**`,
    recommendedDocs: [
      {
        companyId: 'comp-1',
        certificationCode: 'HACCP',
        hierarchyLevel: 'LEVEL_1',
        clauseNumber: '위해요소중점관리',
        code: 'HACCP-M-01',
        title: 'HACCP 관리기준서 (선행요건 및 관리계획)',
        status: 'READY',
        expiryDate: '2027-06-30',
        dDay: 295,
        penaltyRisk: 'HACCP 기준 미준수 시 영업정지 15일 및 과징금 부과',
        summary: '작업장 위생관리, 시설설비 유지 등 선행요건 및 CCP 계획 총괄',
        checklist: [{ text: '중요관리점 결정표 확정', done: true }],
        contentDraft: `# HACCP 관리기준서\n소스류 살균공정 한계기준 관리.`
      }
    ]
  },
  {
    id: 'scenario-4',
    tag: '만기 점검 / 리스크 진단',
    title: '보유 중인 벤처기업 및 ISO 9001 만기 갱신 누락 리스크 사전 진단',
    prompt: '현재 보유하고 있는 벤처기업 확인서와 ISO 9001 인증서의 만기 일자가 얼마 남지 않았습니다. 만약 갱신 시기를 놓쳤을 때 발생하는 법적 과태료, 정부지원사업 제재를 알려주세요.',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    responseAnalysis: `**[만기 누락 리스크 정밀 진단]**
1. **벤처기업인증 만기 누락 시:** 법인세/소득세 50% 감면 소멸
2. **ISO 9001 만기 누락 시:** 조달청 MAS 입찰 자격 정지`,
    recommendedDocs: [
      {
        companyId: 'comp-1',
        certificationCode: 'ISO_9001',
        hierarchyLevel: 'LEVEL_2',
        clauseNumber: 'Clause 9.2 & 9.3',
        code: 'QP-REN-01',
        title: 'ISO 인증 갱신 및 사후관리 심사 대응 절차서',
        status: 'EXPIRING',
        expiryDate: '2026-10-15',
        dDay: 37,
        penaltyRisk: '만기 30일 전 갱신 신청 미접수 시 심사 지연으로 인한 인증 효력 정지',
        summary: '만기 D-90일 전 사후심사 기관 신청, 전년도 시정조치 이행 증빙',
        checklist: [{ text: '심사기관 일정 조율', done: false }],
        contentDraft: `# 갱신 심사 대응 절차서\n만기 60일 전 심사 신청서 제출 필수.`
      }
    ]
  }
];

